# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-01-30 07:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tag',
            old_name='titile',
            new_name='title',
        ),
    ]
